### PR TITLE
feat: Add Navigation/Routing(XD-47)

### PR DESCRIPTION
**Pull request by KonsumGandalf**
features: 
- libs: `facilities-frontend-shell`, `facilities-frontend-shell`, `facilities-frontend-view`, `orders-frontend-shell``
- routing shells
- not found page
- root layout

### CODE REVIEW

**Comment by IngoSternberg** [comment]
I just looked at it a little and I noticed that the test and build failed. But when I ran it locally it worked after deleting the node_modules folder and doing pnpm i again. The header definitely looks nice.

I will try to use and test it tomorrow together with @PatrickSchm1dt and @HaruspexSan and then finish the review

**Review by HaruspexSan — APPROVED** [review]
this is a temporary approval, to get things going .
looks good on first sight though.

**Comment by IngoSternberg** [comment]
I looked at it together with @PatrickSchm1dt and @HaruspexSan and it seems to be working. We need to start with the frame application now and just have to get the current state on develop to begin with the other issues. In case our quick fix of the build/test was not good or if other things have to be changed we can do another pull request.

**Review by IngoSternberg — APPROVED** [review]
LGTM

**Review by HaruspexSan — APPROVED** [review]
This is my second review, since it was re-request by accident.

**Review by PatrickSchm1dt — APPROVED** [review]

**Review by IngoSternberg — APPROVED** [review]
next approval because of accidental re request

**Pull request merged**
